export const menuItems = [
  {
    category: 'destaques',
    title: 'Combo família Simples',
    description: '04 dog duplo + refrigerante 2 litros dog duplo: pão, 2 salsichas, tomate, maionese, catchup e mostarda. Serve 4 pessoas',
    price: 'A partir de R$ 84,00',
    image: '/fotos/combofanmfel.avif',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'destaques',
    title: 'Combo Casal',
    description: '02 dog frango + 02 batata frita + 1 coca cola 600 ml ou sabores dog frango: pão, salsicha, frango, tomate, maionese, catchup e mostarda. Serve 2 pessoas',
    price: 'A partir de R$ 69,00',
    image: '/fotos/cobocasal.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'destaques',
    title: 'Combo familia feliz',
    description: '04 dog frango + refrigerante 2 litros dog frango: pão, salsicha, frango, tomate, maionese, catchup e mostarda. Serve 4 pessoas',
    price: 'A partir de R$ 102,00',
    image: '/fotos/combofanmfel.avif',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'hotdog',
    title: 'Dog Frango Catupiry',
    description: 'Pão, salsicha, frango, tomate, maionese, catchup, mostarda, Catupiry Original e muçarela.',
    price: 'R$ 33,50',
    image: '/fotos/frcom queijo.JPG',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'hotdog',
    title: 'Dog bacon',
    description: 'Pão, salsicha, bacon, tomate, maionese, catchup e mostarda.',
    price: 'R$ 27,50',
    image: '/fotos-cardapio/5c5fec43-2298-4cee-bc2d-0183e8fac80e.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'burgers',
    title: 'VINI especial',
    description: 'Pão, hambúrguer, mussarela, salsicha, frango, maionese, tomate, mostarda e catchup.',
    price: 'R$ 39,50',
    image: '/fotos/dogvniespecial.JPG',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'hotdog',
    title: 'Dog bacon queijo',
    description: 'Pão, salsicha, bacon, muçarela, tomate, maionese, catchup e mostarda.',
    price: 'R$ 29,00',
    image: '/fotos/BACON C QUEIJO.JPG',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'hotdog',
    title: 'Dog simples',
    description: 'Pão, salsicha, tomate, maionese, catchup e mostarda.',
    price: 'R$ 22,50',
    image: '/fotos-cardapio/183a3a05-6293-42be-b934-bf77a35b6cf8.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'burgers',
    title: 'VINI salada',
    description: 'Pão, 1 hambúrguer, mussarela, presunto, maionese, tomate, alface, mostarda e catchup.',
    price: 'R$ 32,50',
    image: '/fotos-cardapio/202112021230_8S3O_i.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'hotdog',
    title: 'Dog frango',
    description: 'Pão, salsicha, frango, tomate, maionese, catchup e mostarda.',
    price: 'R$ 27,50',
    image: '/fotos/frango.JPG',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'burgers',
    title: 'VINI duplo',
    description: 'Pão, 2 hambúrgueres, mussarela, maionese, tomate, mostarda, catchup e cebola.',
    price: 'R$ 39,50',
    image: '/fotos-cardapio/202112021228_LT1U_i.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'hotdog',
    title: 'Dog calabresa',
    description: 'Pão, salsicha, calabresa, tomate, maionese, catchup, mostarda, mussarela, presunto e cebola com shoyu.',
    price: 'R$ 29,50',
    image: '/fotos-cardapio/202112021232_7II2_i.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'burgers',
    title: 'VINI american',
    description: 'Pão, hambúrguer, muçarela, tomate, maionese, molho american burguer, mostarda, pepino em conserva, alface.',
    price: 'R$ 36,50',
    image: '/fotos-cardapio/202112021230_6H8W_i.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'hotdog',
    title: 'Dog duplo frango',
    description: 'Pão, 2 salsichas, frango, tomate, maionese, catchup e mostarda.',
    price: 'R$ 29,50',
    image: '/fotos-cardapio/202112021232_0JTV_i.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'hotdog',
    title: 'Dog frango picante',
    description: 'Pão, salsicha, maionese, tomate, frango desfiado, molho chipotle, pimenta calabresa e mostarda.',
    price: 'R$ 29,50',
    image: '/fotos-cardapio/202112021240_S685_i.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'burgers',
    title: 'VINI bacon',
    description: 'Pão, hambúrguer, bacon, mussarela, maionese, tomate, mostarda, catchup e cebola.',
    price: 'R$ 37,50',
    image: '/fotos-cardapio/202112021229_U4B3_i.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'hotdog',
    title: 'Dog frango bacon',
    description: 'Pão, salsicha, frango, bacon, tomate, maionese, catchup e mostarda.',
    price: 'R$ 31,50',
    image: '/fotos-cardapio/202112021240_6KQ2_i.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'hotdog',
    title: 'Dog frango defumado',
    description: 'Pão, salsicha, maionese, tomate, frango desfiado, molho barbecue e bacon.',
    price: 'R$ 34,00',
    image: '/fotos-cardapio/202112021241_6L8T_i.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'burgers',
    title: 'VINI egg',
    description: 'Pão, hambúrguer, mussarela, tomate, maionese, catchup, mostarda, presunto, alface e ovo.',
    price: 'R$ 34,00',
    image: '/fotos-cardapio/202112021231_88JO_i.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'hotdog',
    title: 'Dog queijo',
    description: 'Pão, salsicha, muçarela, tomate, maionese, catchup e mostarda.',
    price: 'R$ 25,50',
    image: '/fotos/muçarela.JPG',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'hotdog',
    title: 'Dog frango cremoso',
    description: 'Pão, salsicha, frango, molho especial, tomate, maionese, mostarda, presunto e mussarela.',
    price: 'R$ 33,50',
    image: '/fotos-cardapio/202112021239_8CMN_i.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'hotdog',
    title: 'Dog duplo',
    description: 'Pão, 2 salsichas, tomate, maionese, catchup e mostarda.',
    price: 'R$ 23,50',
    image: '/fotos-cardapio/39df4981-489b-4d0b-bf01-836542d26663.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'burgers',
    title: 'VINI simples',
    description: 'Pão, hambúrguer, mussarela, tomate, maionese, catchup, mostarda e cebola.',
    price: 'R$ 32,00',
    image: '/fotos/carne c queijo.JPG',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'burgers',
    title: 'VINI bbq',
    description: 'Pão de brioche, hambúrguer, alface, tomate, maionese, mussarela, cebola com shoyu e molho barbecue.',
    price: 'R$ 35,00',
    image: '/fotos-cardapio/202112021238_7217_i.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'hotdog',
    title: 'Dog vegetariano',
    description: 'Pão, muçarela, ovo, alface, tomate, cebola com shoyu e maionese.',
    price: 'R$ 25,00',
    image: '/fotos-cardapio/202112021237_3881_i.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'combos',
    title: 'Combo Casal',
    description: '2 Dogs Clássicos + 1 Coca-Cola 600ml. Perfeito para dividir!',
    price: 'R$ 40,00',
    badge: 'Combo',
    badgeClass: 'bs',
    image: '/fotos/cobocasal.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'combos',
    title: 'Combo Família',
    description: '4 Dogs Clássicos + 1 Coca-Cola 2L. Para toda a galera!',
    price: 'R$ 75,00',
    badge: 'Combo',
    badgeClass: 'bs',
    image: '/fotos/combofanmfel.avif',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'batatas',
    title: 'Batata família',
    description: 'Batata frita, bacon e molho a sua escolha',
    price: 'R$ 36,90',
    image: '/fotos-cardapio/202203231025_13M2_i.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'batatas',
    title: 'Batata Individual',
    description: 'Batata frita',
    price: 'R$ 11,90',
    image: '/fotos-cardapio/202203231023_41D2_i.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'batatas',
    title: 'Batata Prime American',
    description: 'Batata frita, bacon e molho american',
    price: 'R$ 25,90',
    image: '/fotos-cardapio/202203231012_I6GY_i.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'batatas',
    title: 'Batata Prime Cheddar',
    description: 'Batata frita, bacon e molho cheddar',
    price: 'R$ 25,90',
    image: '/fotos-cardapio/202203231015_63GN_i.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
    {
    category: 'batatas',
    title: 'Batata Prime Grill',
    description: 'Batata frita, bacon e molho grill - sabor churrasco',
    price: 'R$ 25,90',
    image: '/fotos-cardapio/202203231019_3X0X_i.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'batatas',
    title: 'Batata Prime King',
    description: 'Batata frita, bacon, frango desfiado, catchup, mostarde e maionese',
    price: 'R$ 29,90',
    image: '/fotos-cardapio/202203231021_48F7_i.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'batatas',
    title: 'Batata Prime Picante',
    description: 'Batata frita, bacon, molho chipotle e pimenta calabresa em flocos.',
    price: 'R$ 25,90',
    image: '/fotos-cardapio/202203231004_E5F0_i.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'bebidas',
    title: 'Agua mineral com gás 500ml',
    description: '',
    price: 'R$ 5,00',
    image: '/fotos-cardapio/AGUA.JPG',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'bebidas',
    title: 'Agua mineral sem gás 500 ml',
    description: '',
    price: 'R$ 4,50',
    image: '/fotos-cardapio/AGUA.JPG',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'bebidas',
    title: 'Coca Cola 2l',
    description: '',
    price: 'R$ 17,00',
    image: '/fotos-cardapio/COCA 2 LT.jpeg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'bebidas',
    title: 'Coca-Cola 600ml',
    description: 'Garrafa 600ml',
    price: 'R$ 10,00',
    image: '/fotos-cardapio/COCA600.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'bebidas',
    title: 'Coca-Cola sem Açúcar 350ml',
    description: 'Lata 350ml',
    price: 'R$ 7,50',
    image: '/fotos-cardapio/COCA 350.jpeg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'bebidas',
    title: 'Coca-Cola sem Açúcar 600ml',
    description: 'Garrafa 600ml',
    price: 'R$ 10,00',
    image: '/fotos-cardapio/COCA600.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'bebidas',
    title: 'Fanta Laranja 350ml',
    description: 'Lata 350ml',
    price: 'R$ 7,50',
    image: '/fotos-cardapio/FANTA LARANJA.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'bebidas',
    title: 'Fanta Laranja 600ml',
    description: 'Garrafa 600ml',
    price: 'R$ 10,00',
    image: '/fotos-cardapio/FANTA.jpeg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'bebidas',
    title: 'Fanta Uva 350ml',
    description: 'Lata 350ml',
    price: 'R$ 7,50',
    image: '/fotos-cardapio/FANTA UVA.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'bebidas',
    title: 'Refrigerante Coca Cola Lata 350ml',
    description: '',
    price: 'R$ 7,50',
    image: '/fotos-cardapio/COCA 350.jpeg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'bebidas',
    title: 'Sprite Lemon Fresh 510ml',
    description: 'Garrafa 510ml',
    price: 'R$ 10,00',
    image: '/fotos-cardapio/SPRYTE.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'bebidas',
    title: 'Sprite Original 350ml',
    description: 'Lata 350ml',
    price: 'R$ 7,50',
    image: '/fotos-cardapio/SPRITE .jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'bebidas',
    title: 'Sprite Original 600ml',
    description: 'Garrafa 600ml',
    price: 'R$ 10,00',
    image: '/fotos-cardapio/SPRYTE.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'bebidas',
    title: 'Suco Del Valle Pêssego 290ml',
    description: 'Lata 290ml',
    price: 'R$ 9,00',
    image: '/fotos-cardapio/VALE CAPPO .jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'bebidas',
    title: 'Suco de Uva Prats 300ml',
    description: 'Garrafa 300ml',
    price: 'R$ 10,00',
    image: '/fotos-cardapio/SUCO PRATIS UVA.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'bebidas',
    title: 'Suco Néctar Del Valle Uva 290ml',
    description: '',
    price: 'R$ 9,00',
    image: '/fotos-cardapio/CAPPO VALLE UVA.jpeg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'bebidas',
    title: 'Suco Prats Laranja 900ml',
    description: 'Unidade 900ml',
    price: 'R$ 18,00',
    image: '/fotos-cardapio/SUCO PRATS LARANJA.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'bebidas',
    title: 'Suco Sabor Laranja Prats 300ml',
    description: 'Embalagem 300ml',
    price: 'R$ 10,00',
    image: '/fotos-cardapio/SUCO PRAIS.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  }
];

export const categories = {
  todos: 'Todos',
  destaques: 'Destaques',
  hotdog: '🌭 Hot Dogs',
  burgers: '🍔 Burgers',
  combos: '🎁 Combos',
  batatas: '🍟 Batatas',
  bebidas: '🥤 Bebidas',
};
