export const menuItems = [
  {
    category: 'promocoes',
    title: 'Super Combo Família Simples',
    description: '04 dog duplo + refrigerante 2 litros. Dog Duplo: Pão macio, 2 salsichas, tomate, maionese gourmet, ketchup e mostarda. Serve bem 4 pessoas.',
    price: 'R$ 84,00',
    oldPrice: 'R$ 96,00',
    badge: '12% OFF',
    badgeClass: 'bs',
    image: '/fotos/combofanmfel.avif',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'promocoes',
    title: 'Combo Casal Supremo Oferta',
    description: '02 dog frango + 02 batata frita individual + 1 refrigerante 600ml. Dog Frango: Pão prensado, salsicha, frango desfiado com tempero secreto, tomate, maionese, ketchup e mostarda.',
    price: 'R$ 69,00',
    oldPrice: 'R$ 78,00',
    badge: 'Desconto',
    badgeClass: 'bd',
    image: '/fotos/cobocasal.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'destaques',
    title: 'Dog Frango Picante 🌶️',
    description: 'Pão prensado, salsicha, frango desfiado temperado, molho chipotle especial, pimenta calabresa em flocos, tomate e maionese gourmet.',
    price: 'R$ 31,50',
    badge: 'Novo',
    badgeClass: 'bc',
    image: '/fotos-cardapio/202112021240_S685_i.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'hotdog',
    title: 'Dog Frango Catupiry',
    description: 'Pão prensado, salsicha, frango desfiado com tempero exclusivo, Catupiry Original, muçarela, tomate e maionese.',
    price: 'R$ 33,50',
    image: '/fotos/frcom queijo.JPG',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'hotdog',
    title: 'Dog Frango Especial',
    description: 'Frango desfiado temperado, salsicha, muçarela derretida, tomate e maionese gourmet no pão prensado.',
    price: 'R$ 29,50',
    image: '/fotos/frango.JPG',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'hotdog',
    title: 'Dog Frango Supremo',
    description: 'Pão prensado, salsicha, frango desfiado com tempero exclusivo, tomate, maionese, ketchup e mostarda.',
    price: 'R$ 27,50',
    image: '/fotos/frango.JPG',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'hotdog',
    title: 'Dog Duplo Frango',
    description: '02 Salsichas, frango desfiado temperado, tomate e maionese no pão prensado.',
    price: 'R$ 29,50',
    image: '/fotos-cardapio/202112021232_0JTV_i.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'hotdog',
    title: 'Dog Frango Bacon',
    description: 'O melhor de dois mundos: frango desfiado temperado + bacon crocante e maionese gourmet.',
    price: 'R$ 31,50',
    image: '/fotos-cardapio/202112021240_6KQ2_i.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'hotdog',
    title: 'Dog Frango Defumado',
    description: 'Frango desfiado temperado, molho barbecue especial, bacon crocante e maionese no pão prensado.',
    price: 'R$ 34,00',
    image: '/fotos-cardapio/202112021241_6L8T_i.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'hotdog',
    title: 'Dog Frango Cremoso',
    description: 'Frango desfiado temperado, molho especial da casa, muçarela e maionese no pão prensado.',
    price: 'R$ 33,50',
    image: '/fotos-cardapio/202112021239_8CMN_i.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'hotdog',
    title: 'Dog Bacon Premium',
    description: 'Pão de hot dog prensado, salsicha, bacon crocante em tiras, tomate, maionese, ketchup e mostarda.',
    price: 'R$ 27,50',
    image: '/fotos-cardapio/5c5fec43-2298-4cee-bc2d-0183e8fac80e.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'hotdog',
    title: 'Dog Bacon com Queijo',
    description: 'Pão prensado, salsicha, bacon crocante, muçarela derretida, tomate e maionese.',
    price: 'R$ 29,00',
    image: '/fotos/BACON C QUEIJO.JPG',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'hotdog',
    title: 'Dog Simples Tradicional',
    description: 'O clássico pão com salsicha, tomate picado, maionese, ketchup e mostarda.',
    price: 'R$ 22,50',
    image: '/fotos-cardapio/183a3a05-6293-42be-b934-bf77a35b6cf8.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'hotdog',
    title: 'Dog Calabresa Especial',
    description: 'Pão prensado, salsicha, calabresa frita, muçarela, presunto, alface e cebola ao shoyu.',
    price: 'R$ 29,50',
    image: '/fotos-cardapio/202112021232_7II2_i.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'hotdog',
    title: 'Dog com Queijo',
    description: 'Pão prensado, salsicha, muçarela derretida, tomate, maionese e molhos clássicos.',
    price: 'R$ 25,50',
    image: '/fotos/muçarela.JPG',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'hotdog',
    title: 'Dog Duplo Clássico',
    description: 'Pão macio com duas salsichas, tomate, maionese, ketchup e mostarda.',
    price: 'R$ 23,50',
    image: '/fotos-cardapio/39df4981-489b-4d0b-bf01-836542d26663.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'hotdog',
    title: 'Dog Vegetariano',
    description: 'Pão prensado, muçarela, ovo frito, alface, tomate, cebola ao shoyu e maionese gourmet.',
    price: 'R$ 25,00',
    image: '/fotos-cardapio/202112021237_3881_i.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'burgers',
    title: 'VINI Especial Burger',
    description: 'Hambúrguer suculento, muçarela, salsicha, frango desfiado temperado, maionese, tomate e molo da casa.',
    price: 'R$ 39,50',
    badge: 'X-Tudo',
    badgeClass: 'bs',
    image: '/fotos/dogvniespecial.JPG',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'burgers',
    title: 'VINI Salada Burger',
    description: 'Hambúrguer, muçarela, presunto, alface fresca, tomate, maionese e molhos clássicos.',
    price: 'R$ 32,50',
    image: '/fotos-cardapio/202112021230_8S3O_i.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'burgers',
    title: 'VINI Duplo Burger',
    description: 'Para quem tem fome: 2 hambúrgueres, muçarela em dobro, tomate, maionese e cebola ao shoyu.',
    price: 'R$ 39,50',
    image: '/fotos-cardapio/202112021228_LT1U_i.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'batatas',
    title: 'Batata Prime Família',
    description: 'Porção generosa de batata frita crocante com bacon picadinho e molho especial à sua escolha.',
    price: 'R$ 36,90',
    badge: 'Festa',
    badgeClass: 'bs',
    image: '/fotos-cardapio/202203231025_13M2_i.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'batatas',
    title: 'Batata Prime Individual',
    description: 'Porção de batata frita sequinha e crocante. Perfeita para acompanhar seu Dog.',
    price: 'R$ 11,90',
    image: '/fotos-cardapio/202203231023_41D2_i.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?m=msa',
  },
  {
    category: 'batatas',
    title: 'Batata Prime Cheddar',
    description: 'Batata frita crocante coberta com muito molho cheddar cremoso e bacon.',
    price: 'R$ 25,90',
    image: '/fotos-cardapio/202203231015_63GN_i.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'batatas',
    title: 'Batata Prime Grill',
    description: 'Batata frita, bacon e molho grill - sabor churrasco',
    price: 'R$ 25,90',
    image: '/fotos-cardapio/202203231019_3X0X_i.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'batatas',
    title: 'Batata Prime King',
    description: 'Batata frita, bacon, frango desfiado, catchup, mostarde e maionese',
    price: 'R$ 29,90',
    image: '/fotos-cardapio/202203231021_48F7_i.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'batatas',
    title: 'Batata Prime Picante',
    description: 'Batata frita, bacon, molho chipotle e pimenta calabresa em flocos.',
    price: 'R$ 25,90',
    image: '/fotos-cardapio/202203231004_E5F0_i.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'bebidas',
    title: 'Agua mineral com gás 500ml',
    description: '',
    price: 'R$ 5,00',
    image: '/fotos-cardapio/AGUA.JPG',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'bebidas',
    title: 'Agua mineral sem gás 500 ml',
    description: '',
    price: 'R$ 4,50',
    image: '/fotos-cardapio/AGUA.JPG',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'bebidas',
    title: 'Coca Cola 2l',
    description: '',
    price: 'R$ 17,00',
    image: '/fotos-cardapio/COCA 2 LT.jpeg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'bebidas',
    title: 'Coca Cola 600ml',
    description: '',
    price: 'R$ 10,00',
    image: '/fotos-cardapio/COCA600.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'bebidas',
    title: 'Coca-Cola sem Açúcar 350ml',
    description: 'Lata 350ml',
    price: 'R$ 7,50',
    image: '/fotos-cardapio/COCA 350.jpeg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'bebidas',
    title: 'Coca-Cola sem Açúcar 600ml',
    description: 'Garrafa 600ml',
    price: 'R$ 10,00',
    image: '/fotos-cardapio/COCA600.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'bebidas',
    title: 'Fanta Laranja 350ml',
    description: 'Lata 350ml',
    price: 'R$ 7,50',
    image: '/fotos-cardapio/FANTA LARANJA.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'bebidas',
    title: 'Fanta Laranja 600ml',
    description: 'Garrafa 600ml',
    price: 'R$ 10,00',
    image: '/fotos-cardapio/FANTA.jpeg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'bebidas',
    title: 'Fanta Uva 350ml',
    description: 'Lata 350ml',
    price: 'R$ 7,50',
    image: '/fotos-cardapio/FANTA UVA.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'bebidas',
    title: 'Refrigerante Coca Cola Lata 350ml',
    description: '',
    price: 'R$ 7,50',
    oldPrice: 'R$ 8,50',
    image: '/fotos-cardapio/COCA 350.jpeg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'bebidas',
    title: 'Sprite Lemon Fresh 510ml',
    description: 'Garrafa 510ml',
    price: 'R$ 10,00',
    image: '/fotos-cardapio/SPRYTE.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'bebidas',
    title: 'Sprite Original 350ml',
    description: 'Lata 350ml',
    price: 'R$ 7,50',
    image: '/fotos-cardapio/SPRITE .jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'bebidas',
    title: 'Sprite Original 600ml',
    description: 'Garrafa 600ml',
    price: 'R$ 10,00',
    image: '/fotos-cardapio/SPRYTE.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'bebidas',
    title: 'Suco Del Valle Pêssego 290ml',
    description: 'Lata 290ml',
    price: 'R$ 9,00',
    image: '/fotos-cardapio/VALE CAPPO .jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'bebidas',
    title: 'Suco de Uva Prats 300ml',
    description: 'Garrafa 300ml',
    price: 'R$ 10,00',
    image: '/fotos-cardapio/SUCO PRATIS UVA.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'bebidas',
    title: 'Suco Néctar Del Valle Uva 290ml',
    description: '',
    price: 'R$ 9,00',
    image: '/fotos-cardapio/CAPPO VALLE UVA.jpeg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'bebidas',
    title: 'Suco Prats Laranja 900ml',
    description: 'Natural e fresquinho. Unidade 900ml.',
    price: 'R$ 18,00',
    image: '/fotos-cardapio/SUCO PRATS LARANJA.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'bebidas',
    title: 'Suco Sabor Laranja Prats 300ml',
    description: 'Embalagem 300ml',
    price: 'R$ 10,00',
    image: '/fotos-cardapio/SUCO PRAIS.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  }
];

export const categories = {
  promocoes: 'Promoções',
  destaques: 'Mais Pedidos',
  hotdog: 'Hot Dogs',
  burgers: 'Burgers',
  combos: 'Combos',
  batatas: 'Batatas',
  bebidas: 'Bebidas',
};
