export const menuItems = [
  {
    category: 'destaques',
    title: 'Combo fam├¡lia Simples',
    description: '04 dog duplo + refrigerante 2 litros. Dog Duplo: P├úo macio, 2 salsichas, tomate, maionese gourmet, ketchup e mostarda. Serve bem 4 pessoas.',
    price: 'A partir de R$ 84,00',
    badge: 'Mais Pedido',
    badgeClass: 'bs',
    image: '/fotos/combofanmfel.avif',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'destaques',
    title: 'Combo Casal Supremo',
    description: '02 dog frango + 02 batata frita individual + 1 refrigerante 600ml. Dog Frango: P├úo prensado, salsicha, frango desfiado com tempero secreto, tomate, maionese, ketchup e mostarda.',
    price: 'A partir de R$ 69,00',
    badge: 'Popular',
    badgeClass: 'bd',
    image: '/fotos/cobocasal.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'destaques',
    title: 'Dog Frango Picante ­ƒîÂ´©Å',
    description: 'P├úo prensado, salsicha, frango desfiado temperado, molho chipotle especial, pimenta calabresa em flocos, tomate e maionese gourmet.',
    price: 'R$ 31,50',
    badge: 'Novo',
    badgeClass: 'bc',
    image: '/fotos-cardapio/202112021240_S685_i.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'hotdog_frango',
    title: 'Dog Frango Catupiry',
    description: 'P├úo prensado, salsicha, frango desfiado com tempero exclusivo, Catupiry Original, mu├ºarela, tomate e maionese.',
    price: 'R$ 33,50',
    image: '/fotos/frcom queijo.JPG',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'hotdog_frango',
    title: 'Dog Frango Especial',
    description: 'Frango desfiado temperado, salsicha, mu├ºarela derretida, tomate e maionese gourmet no p├úo prensado.',
    price: 'R$ 29,50',
    image: '/fotos/frango.JPG',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'hotdog',
    title: 'Dog Bacon Premium',
    description: 'P├úo de hot dog prensado, salsicha, bacon crocante em tiras, tomate, maionese, ketchup e mostarda.',
    price: 'R$ 27,50',
    image: '/fotos-cardapio/5c5fec43-2298-4cee-bc2d-0183e8fac80e.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'burgers',
    title: 'VINI Especial Burger',
    description: 'Hamb├║rguer suculento, mu├ºarela, salsicha, frango desfiado temperado, maionese, tomate e molo da casa.',
    price: 'R$ 39,50',
    badge: 'X-Tudo',
    badgeClass: 'bs',
    image: '/fotos/dogvniespecial.JPG',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'hotdog',
    title: 'Dog Bacon com Queijo',
    description: 'P├úo prensado, salsicha, bacon crocante, mu├ºarela derretida, tomate e maionese.',
    price: 'R$ 29,00',
    image: '/fotos/BACON C QUEIJO.JPG',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'hotdog',
    title: 'Dog Simples Tradicional',
    description: 'O cl├íssico p├úo com salsicha, tomate picado, maionese, ketchup e mostarda.',
    price: 'R$ 22,50',
    image: '/fotos-cardapio/183a3a05-6293-42be-b934-bf77a35b6cf8.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'burgers',
    title: 'VINI Salada Burger',
    description: 'Hamb├║rguer, mu├ºarela, presunto, alface fresca, tomate, maionese e molhos cl├íssicos.',
    price: 'R$ 32,50',
    image: '/fotos-cardapio/202112021230_8S3O_i.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'hotdog_frango',
    title: 'Dog Frango Supremo',
    description: 'P├úo prensado, salsicha, frango desfiado com tempero exclusivo, tomate, maionese, ketchup e mostarda.',
    price: 'R$ 27,50',
    image: '/fotos/frango.JPG',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'burgers',
    title: 'VINI Duplo Burger',
    description: 'Para quem tem fome: 2 hamb├║rgueres, mu├ºarela em dobro, tomate, maionese e cebola ao shoyu.',
    price: 'R$ 39,50',
    image: '/fotos-cardapio/202112021228_LT1U_i.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'hotdog',
    title: 'Dog Calabresa Especial',
    description: 'P├úo prensado, salsicha, calabresa frita, mu├ºarela, presunto, alface e cebola ao shoyu.',
    price: 'R$ 29,50',
    image: '/fotos-cardapio/202112021232_7II2_i.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'hotdog_frango',
    title: 'Dog Duplo Frango',
    description: '02 Salsichas, frango desfiado temperado, tomate e maionese no p├úo prensado.',
    price: 'R$ 29,50',
    image: '/fotos-cardapio/202112021232_0JTV_i.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'hotdog_frango',
    title: 'Dog Frango Bacon',
    description: 'O melhor de dois mundos: frango desfiado temperado + bacon crocante e maionese gourmet.',
    price: 'R$ 31,50',
    image: '/fotos-cardapio/202112021240_6KQ2_i.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'hotdog_frango',
    title: 'Dog Frango Defumado',
    description: 'Frango desfiado temperado, molho barbecue especial, bacon crocante e maionese no p├úo prensado.',
    price: 'R$ 34,00',
    image: '/fotos-cardapio/202112021241_6L8T_i.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'hotdog',
    title: 'Dog com Queijo',
    description: 'P├úo prensado, salsicha, mu├ºarela derretida, tomate, maionese e molhos cl├íssicos.',
    price: 'R$ 25,50',
    image: '/fotos/mu├ºarela.JPG',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'hotdog_frango',
    title: 'Dog Frango Cremoso',
    description: 'Frango desfiado temperado, molho especial da casa, mu├ºarela e maionese no p├úo prensado.',
    price: 'R$ 33,50',
    image: '/fotos-cardapio/202112021239_8CMN_i.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'hotdog',
    title: 'Dog Duplo Cl├íssico',
    description: 'P├úo macio com duas salsichas, tomate, maionese, ketchup e mostarda.',
    price: 'R$ 23,50',
    image: '/fotos-cardapio/39df4981-489b-4d0b-bf01-836542d26663.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'hotdog',
    title: 'Dog Vegetariano',
    description: 'P├úo prensado, mu├ºarela, ovo frito, alface, tomate, cebola ao shoyu e maionese gourmet.',
    price: 'R$ 25,00',
    image: '/fotos-cardapio/202112021237_3881_i.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'batatas',
    title: 'Batata Prime Fam├¡lia',
    description: 'Por├º├úo generosa de batata frita crocante com bacon picadinho e molho especial ├á sua escolha.',
    price: 'R$ 36,90',
    badge: 'Festa',
    badgeClass: 'bs',
    image: '/fotos-cardapio/202203231025_13M2_i.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'batatas',
    title: 'Batata Prime Individual',
    description: 'Por├º├úo de batata frita sequinha e crocante. Perfeita para acompanhar seu Dog.',
    price: 'R$ 11,90',
    image: '/fotos-cardapio/202203231023_41D2_i.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'batatas',
    title: 'Batata Prime Cheddar',
    description: 'Batata frita crocante coberta com muito molho cheddar cremoso e bacon.',
    price: 'R$ 25,90',
    image: '/fotos-cardapio/202203231015_63GN_i.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'batatas',
    title: 'Batata Prime Grill',
    description: 'Batata frita com sabor churrasco! Acompanha bacon e molho grill exclusivo.',
    price: 'R$ 25,90',
    image: '/fotos-cardapio/202203231019_3X0X_i.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'batatas',
    title: 'Batata Prime King',
    description: 'A completa: batata frita, bacon, frango desfiado temperado e mix de molhos cl├íssicos.',
    price: 'R$ 29,90',
    image: '/fotos-cardapio/202203231021_48F7_i.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'batatas',
    title: 'Batata Prime Picante',
    description: 'Para quem curte um toque ardente: batata frita, bacon, molho chipotle e pimenta calabresa em flocos.',
    price: 'R$ 25,90',
    image: '/fotos-cardapio/202203231004_E5F0_i.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'bebidas',
    title: 'Agua mineral sem g├ís 500 ml',
    description: '',
    price: 'R$ 4,50',
    image: '/fotos-cardapio/AGUA.JPG',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'bebidas',
    title: 'Coca-Cola 2L',
    description: '',
    price: 'R$ 17,00',
    image: '/fotos-cardapio/COCA 2 LT.jpeg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'bebidas',
    title: 'Coca-Cola 600ml',
    description: 'Garrafa 600ml',
    price: 'R$ 10,00',
    image: '/fotos-cardapio/COCA600.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'bebidas',
    title: 'Coca-Cola 350ml',
    description: 'Lata 350ml',
    price: 'R$ 7,50',
    image: '/fotos-cardapio/COCA 350.jpeg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  },
  {
    category: 'bebidas',
    title: 'Suco Prats Laranja 900ml',
    description: 'Natural e fresquinho. Unidade 900ml.',
    price: 'R$ 18,00',
    image: '/fotos-cardapio/SUCO PRATS LARANJA.jpg',
    ifoodUrl: 'https://www.ifood.com.br/delivery/taquara-rs/hot-dog-do-vini-recreio',
    anotaaiUrl: 'https://pedido.anota.ai/loja/marcos-vinicius-dresbach-do-amaral-ltda?f=msa',
  }
];

export const categories = {
  todos: 'Todos',
  destaques: '­ƒöÑ Os Mais Pedidos',
  hotdog: '­ƒî¡ Cl├íssicos Prensados',
  hotdog_frango: '­ƒìù Frango Supremo',
  batatas: '­ƒìƒ Batatas Prime',
  burgers: '­ƒìö Burgers do Vini',
  combos: '­ƒÄü Combos Econ├┤micos',
  bebidas: '­ƒÑñ Bebidas',
};
ü Combos',
  batatas: '­ƒìƒ Batatas',
  bebidas: '­ƒÑñ Bebidas',
};
